# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      DATABASE_NAME: meal_plan_db
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_PASSWORD: $DB_PASSWORD
      DB_USERNAME: $DB_USER
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT