name: Push docker image

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitLab
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.CI_REGISTRY }}
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}
      - name: Build the Docker image
        run: |
          docker build -t registry.gitlab.com/tmbh/meal-plan-admin-pipeline:${{ github.sha }} .
          docker push registry.gitlab.com/tmbh/meal-plan-admin-pipeline:${{ github.sha }}
